### ISSUE TITLE
Villager Ui issue + Some incompatibility 

### ISSUE THREAD

**Issue by ZcamZone** [Shrimpsnail/Immersive-Interfaces#1]
downloading this test pack was a good excuse to hop on my own singleplayer world

So..
![image_2024-08-06_173522326](https://github.com/user-attachments/assets/740e08e1-e52a-44de-96c4-150e75c4c7e8)
![image_2024-08-06_173542031](https://github.com/user-attachments/assets/228b19e5-3310-4c8f-a267-898b25a37712)
The villager progress bar was taken out for whatever reason

On unrelated news, the pack now does this with the Jade mod on fabric:
![image_2024-08-06_173703882](https://github.com/user-attachments/assets/993bdd24-c360-4ada-bcf1-7db2edb64a82)
![image](https://github.com/user-attachments/assets/e3ace901-7bd2-4f8c-bf94-90f29320d143)

But not with the Barrel viewer:
![image_2024-08-06_173823202](https://github.com/user-attachments/assets/d603e910-5d42-40dd-a168-bdb996b63598)

Thats all, My friends and I are a big fan of your work
Keep it up @Shrimpsnail ^^

**Comment by Shrimpsnail** [comment]
to bring up the points, the experience bar is in a really terrible spot, i might experiment making it smaller or by perhaps dots to make it at least visible

The barrel not having the Chest issue is odd as both use container name. I assume barrel checks for the block name instead, this might not be fixable

Due to the villager containing "- Novice" which has been removed in the current text, I'm confident it can be mitigated, however it will likely not show any profession name.

i will be investigating these issues thank you for bringing them up!

**Comment by ZcamZone** [comment]
I think you're right on the name thing
![image](https://github.com/user-attachments/assets/73dd30fb-3c93-4612-8a7d-2c6141d28917)
![image](https://github.com/user-attachments/assets/2289ff4f-e588-4be5-b673-f0f96ded69f7)
This chest was renamed and now it's using the "Generic" texture you made (The chest boat does this too)

Only the Chest, Double Chest, and Chest Minecart have this issue
I'll see if i can figure something out

**Comment by Shrimpsnail** [comment]
Chest boat sadly uses the item name for it's container name i have experimented with giving it a custom texture but have been unsuccessful

**Comment by ZcamZone** [comment]
Could the generic_54 container just be changed with fonts, like making it into the chest texture?

**Comment by Shrimpsnail** [comment]
Changing the texture itself comes with some issues, mainly it reduces the size i have to work with, as chests expand past the ui by a bit, it requires the barrel to be bigger so it can hide all of the chest ui underneath and it also comes with problems when dealing with the double chests because generic 54 uses the same texture for small and large ones

**Comment by ZcamZone** [comment]
im a big enough fan to toggle the mod off while i dont need it to see the textures
Thanks for responding, have a good day/night
