### ISSUE TITLE
chests do NOT work

### ISSUE THREAD

**Issue by AzureAxi** [Shrimpsnail/Immersive-Interfaces#31]
man i love this resourcepack but the chest is invisible 
you can still open it and show the gui but also if you do the command /give on a player
its gonna show the whole chest gui in chat which is awful for me..
same problem applies to ender chest

**Comment by Shrimpsnail** [comment]
The chest is invisible? what part of it is invisible? name, ui, maybe it's using the base ui without the chest?

Regarding giving, using the vanilla format there's nothing i can do, i'm working on polytone features that fix all those issues, but in vanilla the font is needed, although i assumed mojang would be using item names not container names for that

**Comment by Shrimpsnail** [comment]
it's bigger, but it's only bigger because it was already decided it was going to use a langfile, i have old chests that fit 

i need the file because all the chests use the same texture, and having for example if i add a chest texture it would apply to everything, and if i try to add then with lang files there wouldn't really be a fix and it would cause issues in the barrel or large chest with how the texture is setup and they would have to compensate.

**Comment by AzureAxi** [comment]
> The chest is invisible? what part of it is invisible? name, ui, maybe it's using the base ui without the chest?
> 
> Regarding giving, using the vanilla format there's nothing i can do, i'm working on polytone features that fix all those issues, but in vanilla the font is needed, although i assumed mojang would be using item names not container names for that

So, the invisible chest bug is fixed for me but im using excalibur resourcepack and it does not seem to change the textures of the chest it is still vanilla not excalibur chest..

**Comment by Shrimpsnail** [comment]
My pack has no changes related to the actual chest textures or models, the entire ui disapears or the actual chest?
