### ISSUE TITLE
Strange Texturing anomaly 

### ISSUE THREAD

**Issue by LloydValkyria** [Shrimpsnail/Immersive-Interfaces#7]
I am absolutely in love with the texture pack and keep checking back daily for updates. I just wanted to bring to your attention some issues I found that I figured to mention.
![2024-09-12_02 24 20](https://github.com/user-attachments/assets/4a6ac873-bdbd-41a6-bc00-9e065be4468f)
![2024-09-12_01 26 59](https://github.com/user-attachments/assets/50a6df60-0d7f-478d-86f1-96f36a339420)
- So issue one I have found involves any of the chest inventories. Echest, doublechest, chest, enderchest, barrel, and minecart chest.
If a piece of gear, tool, or anything that has a durability bar is put into any of these storage containers any part of the durability bar that isn't overlaying a part of the item just disappears making the bar look spotty or straight disappear. However, it's only in the containers but it's perfectly normal in the inventory and anything not a chest-related container. Not too big of a deal.

- Issue two that I've spotted, and I've never seen this before but when you got to summon a minecart chest, instead of the item name popping up in the chat saying you just summoned it, the whole inventory of the minecart chest gets posted in the chat like an image. Again not a big deal because who spawns those specifically and it only appears doing that and to me it's kinda funny. 🤣

**Comment by Shrimpsnail** [comment]
these are caused by the fact the entities are simply called the ui. the minecart summons has more issues when paired to mods that show the names.

the durability bar is a consequence of this, font renders in front of the durability bars but behind the item, and the item renders behind the bars, which makes them only visible in front of items, There might be a possibility where vanilla shaders can help with this but other than that there is nothing i can do.

**Comment by Shrimpsnail** [comment]
Has that worked? i did not get it to work on 1.21
